image: dtannock/beanstalkd:1.10
imagePullPolicy: IfNotPresent

replicaCount: 1

pdbMinAvailable: 1

AntiAffinity: "hard"

beanstalkd:
  maxJobSize: 65535
  binlogSize: "20Mi"

service:
  port: 11300

metrics:
  enabled: false
  image: dtannock/beanstalkd-exporter:0.1.1
  imagePullPolicy: IfNotPresent
  port: 11301
